FROM debian:bookworm-slim

RUN sed -i '/\/usr\/share\/man\/\*/d' /etc/dpkg/dpkg.cfg.d/docker \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
      bzip2 diffutils file gzip less locate man-db manpages nano procps rsync sudo tar unzip vim xz-utils zip \
    && apt-get install -y --reinstall coreutils \
    && mandb --quiet \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd laboratorio \
    && useradd --create-home --shell /bin/bash --groups laboratorio aluno
USER aluno
WORKDIR /home/aluno

CMD ["sleep", "infinity"]
